In [1]:
import numpy as np
import pandas as pd
data = {
    'Country': ['UK', 'China', 'France', 'China', 'UK',
                'France', 'China', 'UK', 'France', 'China'],

    'Age': [22, 34, 26, 41, np.nan,
            30, 37, 28, 45, 32],

    'Salary': [30000, 58000, 47000, 76000, 65000,
               np.nan, 71000, 39000, 92000, 54000],

    'Purchased': ['Yes', 'No', 'Yes', 'No', 'Yes',
                  'No', 'Yes', 'No', 'Yes', 'No']
}

df = pd.DataFrame(data)

print("Original Dataset:")
print(df)

df['Country'] = df['Country'].fillna(df['Country'].mode()[0])

features = df.iloc[:, :-1].values
label = df.iloc[:, -1].values

from sklearn.impute import SimpleImputer

age = SimpleImputer(strategy='mean')
salary = SimpleImputer(strategy='mean')

features[:, [1]] = age.fit_transform(features[:, [1]])
features[:, [2]] = salary.fit_transform(features[:, [2]])

print("\nFeatures after handling missing values:")
print(features)

from sklearn.preprocessing import OneHotEncoder

oh = OneHotEncoder(sparse_output=False)

Country = oh.fit_transform(features[:, [0]])

print("\nEncoded Country:")
print(Country)

final_set = np.concatenate(
    (Country, features[:, [1, 2]]),
    axis=1
)

print("\nFinal Set:")
print(final_set)

from sklearn.preprocessing import StandardScaler

sc = StandardScaler()

feat_standard_scaler = sc.fit_transform(final_set)

print("\nStandard Scaled Data:")
print(feat_standard_scaler)


# Min-Max Scaling
from sklearn.preprocessing import MinMaxScaler

mms = MinMaxScaler(feature_range=(0, 1))

feat_minmax_scaler = mms.fit_transform(final_set)

print("\nMin-Max Scaled Data:")
print(feat_minmax_scaler)

Original Dataset:
  Country   Age   Salary Purchased
0      UK  22.0  30000.0       Yes
1   China  34.0  58000.0        No
2  France  26.0  47000.0       Yes
3   China  41.0  76000.0        No
4      UK   NaN  65000.0       Yes
5  France  30.0      NaN        No
6   China  37.0  71000.0       Yes
7      UK  28.0  39000.0        No
8  France  45.0  92000.0       Yes
9   China  32.0  54000.0        No

Features after handling missing values:
[['UK' 22.0 30000.0]
 ['China' 34.0 58000.0]
 ['France' 26.0 47000.0]
 ['China' 41.0 76000.0]
 ['UK' 32.77777777777778 65000.0]
 ['France' 30.0 59111.11111111111]
 ['China' 37.0 71000.0]
 ['UK' 28.0 39000.0]
 ['France' 45.0 92000.0]
 ['China' 32.0 54000.0]]

Encoded Country:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]

Final Set:
[[0.0 0.0 1.0 22.0 30000.0]
 [1.0 0.0 0.0 34.0 58000.0]
 [0.0 1.0 0.0 26.0 47000.0]
 [1.0 0.0 0.0 41.0 76000.0]
 [0.0 0.0 1.0 32.77777777777778 650